- name: Update and upgrade all ubuntu packages
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
 
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world
 
    - name: update all packages (apt update)
      apt:
        update_cache: yes
        cache_valid_time: 3600
 
    - name: upgrade all packages (apt upgrade)
      apt:
        upgrade: yes
 
    - name: Install needed system packages
      apt:
        name:
           - apt-transport-https
           - ca-certificates
           - curl
           - gnupg
           - lsb-release
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
    
    - name: Install python3-venv
      apt:
        name: python3-venv
        state: present

    - name: Check if Docker is already installed
      command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present


    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker


    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
        cache_valid_time: 3600


    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
      when: docker_check.rc != 0

    - name: Ensure Docker is enabled and running
      service:
        name: docker
        state: started
        enabled: yes
