- name: Ensure venv parent directory exists
  file:
    path: /opt/myenv
    state: directory
    mode: '0755'

- name: Create virtual environment
  command: python3 -m venv /opt/myenv/venv
  args:
    creates: /opt/myenv/venv/bin/activate

- name: Upgrade pip in virtualenv
  command: /opt/myenv/venv/bin/pip install --upgrade pip

- name: Install requirements into virtualenv
  pip:
    requirements: "{{ requirements_path }}"
    executable: /opt/myenv/venv/bin/pip

- name: Add virtualenv activation to .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'source /opt/myenv/venv/bin/activate'
    insertafter: EOF

- name: Ensure /usr/bin/python symlink exists
  file:
    src: /opt/myenv/venv/bin/python
    dest: /usr/bin/python
    state: link
  when: ansible_facts['distribution'] == "Ubuntu"